name: Compile and Run Static Code Analysis

on:
  push:
    paths-ignore:
    - .gitignore
    - docs/images/*
    - docs/*
    - LICENSE
    - README.md
    - scripts/release_version.txt
    branches:
      - master
      - release/HyScale*
  pull_request:
    paths-ignore:
    - .gitignore
    - docs/images/*
    - docs/*
    - LICENSE
    #- README.md
    - scripts/release_version.txt
    branches: [ master ]

jobs:
  compile:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
              java: [ 11 ]
    name: Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - shell: bash
        run: |
         echo "Running Static Code Analysis"
