# Build workflow gets auto triggered upon code merge to master or release* branches

name: Upload Release Asset

on:
  push:
    branches:
    - master
    - Release*
    paths:
      - 'test/a.txt'

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow
    - name: release_info # This would actually build your project, using zip for an example artifact
      id: release_info
      if: github.ref == 'refs/heads/master'
      run: |
         ./publish_artifacts.sh
         echo ::set-output name=CHANGELOG::$(echo -e "${CHANGELOG}")
         echo ${GITHUB_REF##*/}
         docker run -v $(pwd):/var/tmp --entrypoint /bin/cp  srujan5140/hyscale:$(cat test/a.txt) /usr/local/bin/hyscale.jar /var/tmp
         echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
