
name: Upload Release Asset

on:
  push:
    paths-ignore:
    - test/a.txt
    branches:
    - master
    - Release*
    - release/HyScale*
  create:
    branch:
    - release/Hyscale*

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow
    - name: release_info # This would actually build your project, using zip for an example artifact
      id: release_info
      run: |
         ./publish_artifacts.sh
         echo ::set-output name=CHANGELOG::$(echo -e "${CHANGELOG}")
         docker run -v $(pwd):/var/tmp --entrypoint /bin/cp  srujan5140/hyscale:0.9.5.18 /usr/local/bin/hyscale.jar /var/tmp
         echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
